In [1]:
import numpy as np

In [2]:
import scipy.io
# TDT2 dataset
tdt2_dataSet = scipy.io.loadmat("TDT2.mat")
tdt2_dataSet

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Apr 25 13:53:55 2007',
 '__version__': '1.0',
 '__globals__': [],
 'gnd': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [30],
        [30],
        [30]], dtype=uint8),
 'fea': <9394x36771 sparse matrix of type '<class 'numpy.float64'>'
 	with 1224135 stored elements in Compressed Sparse Column format>}

In [3]:
fea_tdt2 = tdt2_dataSet.get('fea')
gnd_tdt2 = tdt2_dataSet.get('gnd')

In [4]:
# number of documents in each category
counter_tdt2 = np.zeros((30))
for i in gnd_tdt2:
    counter_tdt2[i-1] = counter_tdt2[i-1] + 1
counter_tdt2=np.array(counter_tdt2)
counter_tdt2

array([1844., 1828., 1222.,  811.,  441.,  407.,  272.,  238.,  226.,
        167.,  160.,  145.,  141.,  140.,  131.,  123.,  123.,  120.,
        104.,   98.,   76.,   74.,   72.,   71.,   66.,   65.,   63.,
         58.,   56.,   52.])

In [5]:
Top10_tdt2 = counter_tdt2[:10]
Top10_tdt2

array([1844., 1828., 1222.,  811.,  441.,  407.,  272.,  238.,  226.,
        167.])

In [6]:
num_top10_tdt2=np.sum(Top10_tdt2)
num_top10_tdt2

7456.0

In [7]:
import math
Top10_tdt2_10percent=[]
for i in Top10_tdt2:
    Top10_tdt2_10percent.append(math.ceil(i*0.1))
Top10_tdt2_10percent

[185, 183, 123, 82, 45, 41, 28, 24, 23, 17]

In [8]:
num_top10_tdt2_10percent=np.sum(Top10_tdt2_10percent)
num_top10_tdt2_10percent

751

In [9]:
matrix_tdt2 = fea_tdt2.toarray()
matrix_tdt2

array([[2., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 2., 0., ..., 0., 0., 0.],
       [0., 2., 2., ..., 0., 0., 0.]])

In [10]:
np.shape(matrix_tdt2)

(9394, 36771)

In [11]:
# Top 10 of TDT2
matrix_tdt2_top10=matrix_tdt2[:int(np.sum(Top10_tdt2))]
matrix_tdt2_top10

array([[2., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 6., 0., ..., 0., 0., 0.]])

In [12]:
matrix_tdt2_top10.shape

(7456, 36771)

In [13]:
matrix_tdt2_top10_10percent = []
e = 0
for i in range(10):
    tp = Top10_tdt2_10percent[i]
    indices = np.random.choice(range(e, e + int(Top10_tdt2[i])), size=tp, replace=False)
    mp = matrix_tdt2_top10[indices]
    
    for j in mp:
        matrix_tdt2_top10_10percent.append(list(j))
    
    e += int(Top10_tdt2[i])


In [14]:
np.shape(matrix_tdt2_top10_10percent)

(751, 36771)

In [15]:
# function for K-Means
from sklearn.cluster import KMeans
def kmeans(num_clusters,matrix):
    kmeans = KMeans(n_clusters=num_clusters, random_state=0).fit(matrix)
    clusters=kmeans.predict(matrix)
    return clusters

In [16]:
# Kmeans for Top 10 of TDT2
clusters_tdt2_top10=kmeans(10,matrix_tdt2_top10_10percent)
clusters_tdt2_top10

c:\Users\AFRAA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


array([9, 9, 9, 9, 9, 9, 9, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 1, 9, 1, 9, 9, 9, 9, 9, 9, 4, 9, 9, 9, 1, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 1, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 1, 9, 9, 9, 9, 9, 9,
       9, 9, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 1, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 1, 1, 9, 9, 9, 1, 9, 9, 9, 1, 9, 1, 9,
       9, 1, 1, 9, 9, 9, 9, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 1, 9, 9, 1, 9, 9, 1, 9, 9, 9, 1, 9, 4, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 1, 9, 9, 8, 9, 1, 8, 8, 9, 8, 9, 9, 8, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 8, 8, 9, 8, 9, 9, 8, 9, 7, 9, 9, 8, 9, 8, 9,
       8, 8, 9, 9, 9, 9, 8, 9, 8, 8, 9, 9, 9, 8, 9, 9, 9, 9, 8, 8, 9, 1,
       7, 8, 9, 9, 8, 9, 9, 8, 9, 8, 8, 9, 8, 8, 8, 9, 9, 8, 9, 9, 9, 9,
       9, 8, 9, 8, 9, 9, 9, 9, 7, 9, 9, 8, 8, 8, 9, 9, 9, 8, 8, 7, 9, 9,
       9, 8, 9, 8, 9, 9, 8, 9, 9, 9, 9, 9, 7, 8, 8,

In [17]:
# function for calculating purity
def purity(num_clusters,list1,list2):
    sum=0
    for i in range(num_clusters):
        counter1 = np.zeros((num_clusters))
        w=0
        for j in range(len(list1)):
            k=int(list1[j])
            t = w + k
            for k in list2[w:t]:
                if(k==i):
                    counter1[j]=counter1[j] + 1
            w=t 
        sum=sum+max(counter1)
    purity=sum/ int(np.sum(list1))
    return purity

In [18]:
# purity of Kmeans clustering for Top 10 of TDT2
purity_kmeans_top10_tdt2=purity(10,Top10_tdt2_10percent,clusters_tdt2_top10)
purity_kmeans_top10_tdt2

0.36617842876165113

In [19]:
# functin for number of documents in each cluster
def num_of_docs_each_cluster(num_clusters,list):
    counter_clusters = np.zeros((num_clusters))
    for i in list:
        counter_clusters[i] = counter_clusters[i] + 1
    counter_clusters=np.array(counter_clusters)
    return counter_clusters

In [20]:
# function for calculating entropy
import math
def entropy(num_clusters,list1,list2):
    sum2=0
    for i in range(num_clusters):
        sum1=0
        w=0
        for j in range(len(list1)):
            counter2=0
            k=int(list1[j])
            t = w + k
            for k in list2[w:t]:
                if(k==i):
                    counter2 +=1
            w=t
            if(counter2 !=0):
                sum1=sum1+ counter2* (math.log(counter2/(int(num_of_docs_each_cluster(num_clusters,list2)[i]))))
        sum2=sum2+sum1
    entropy= (-1)*sum2/ (int(np.sum(list1)*math.log(len(list1))))
    return entropy

In [21]:
# entropy of Kmeans clustering for Top 10 of TDT2
entropy_kmeans_top10_tdt2=entropy(10,Top10_tdt2_10percent,clusters_tdt2_top10)
entropy_kmeans_top10_tdt2

0.7488102085945022

In [22]:
# function for NMF
from sklearn.decomposition import NMF
def nmf(num_clusters,matrix):
    model = NMF(n_components=num_clusters,init='nndsvda', random_state=0)
    W = model.fit_transform(matrix)
    H = model.components_
    return W,H

In [23]:
# NMF for Top 10 of TDT2
W_tdt2_top10,H_tdt2_top10=nmf(10,matrix_tdt2_top10_10percent)

In [24]:
W_tdt2_top10.shape

(751, 10)

In [25]:
H_tdt2_top10.shape

(10, 36771)

In [26]:
# clusters of documents with NMF for Top 10 of TDT2
max_index_tdt2_top10=[]
for document in W_tdt2_top10:
    max_index_tdt2_top10.append(np.argmax(document))
max_index_tdt2_top10

[6,
 6,
 9,
 0,
 7,
 0,
 6,
 2,
 6,
 7,
 0,
 6,
 6,
 9,
 6,
 6,
 0,
 7,
 0,
 6,
 6,
 6,
 6,
 9,
 7,
 0,
 6,
 9,
 6,
 9,
 6,
 0,
 6,
 6,
 9,
 6,
 6,
 6,
 7,
 6,
 6,
 8,
 6,
 0,
 6,
 6,
 6,
 0,
 0,
 7,
 0,
 0,
 6,
 6,
 6,
 7,
 6,
 0,
 6,
 6,
 0,
 6,
 6,
 0,
 0,
 6,
 6,
 6,
 6,
 7,
 7,
 6,
 7,
 6,
 0,
 6,
 0,
 6,
 6,
 6,
 6,
 6,
 9,
 8,
 6,
 6,
 0,
 6,
 6,
 2,
 6,
 0,
 6,
 6,
 6,
 6,
 3,
 6,
 6,
 0,
 0,
 7,
 6,
 6,
 0,
 0,
 6,
 6,
 6,
 0,
 6,
 6,
 7,
 0,
 0,
 6,
 6,
 6,
 6,
 0,
 6,
 6,
 6,
 6,
 6,
 0,
 6,
 9,
 0,
 6,
 2,
 0,
 6,
 0,
 0,
 6,
 6,
 6,
 6,
 0,
 6,
 6,
 6,
 6,
 6,
 9,
 6,
 0,
 0,
 6,
 6,
 0,
 6,
 0,
 6,
 7,
 6,
 0,
 5,
 0,
 6,
 0,
 6,
 0,
 6,
 6,
 6,
 6,
 2,
 6,
 6,
 6,
 7,
 6,
 0,
 6,
 6,
 6,
 6,
 7,
 6,
 0,
 6,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 9,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 1,
 1,
 1,
 9,
 1,
 1,
 1,
 1,
 1,


In [27]:
# purity of NMF clustering for Top 10 of TDT2
purity_nmf_top10_tdt2=purity(10,Top10_tdt2_10percent,max_index_tdt2_top10)
purity_nmf_top10_tdt2

0.8229027962716379

In [28]:
# entropy of NMF clustering for Top 10 of TDT2
entropy_nmf_top10_tdt2=entropy(10,Top10_tdt2_10percent,max_index_tdt2_top10)
entropy_nmf_top10_tdt2

0.24353823294249632

In [29]:
# Last 10 of TDT2
Last10_tdt2 =counter_tdt2[-10:]
Last10_tdt2

array([76., 74., 72., 71., 66., 65., 63., 58., 56., 52.])

In [30]:
num_last10_tdt2=np.sum(Last10_tdt2)
num_last10_tdt2

653.0

In [31]:
matrix_tdt2_last10=matrix_tdt2[-int(num_last10_tdt2):]
matrix_tdt2_last10

array([[8., 5., 1., ..., 0., 0., 0.],
       [9., 0., 1., ..., 0., 0., 0.],
       [4., 2., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 2., 0., ..., 0., 0., 0.],
       [0., 2., 2., ..., 0., 0., 0.]])

In [32]:
matrix_tdt2_last10.shape

(653, 36771)

In [33]:
# Kmeans for Last 10 of TDT2
clusters_tdt2_last10=kmeans(10,matrix_tdt2_last10)

c:\Users\AFRAA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [34]:
# clusters of documents with Kmeans for Last 10 of TDT2
clusters_tdt2_last10

array([9, 9, 9, 9, 9, 9, 2, 2, 2, 2, 9, 2, 3, 9, 9, 9, 3, 9, 9, 2, 9, 9,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 9, 9, 2, 2, 2, 2, 9, 2, 9, 2,
       9, 9, 9, 9, 9, 9, 9, 2, 9, 9, 9, 9, 9, 9, 9, 9, 2, 9, 9, 9, 2, 2,
       2, 2, 2, 9, 9, 2, 3, 9, 2, 9, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 2, 7, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 3, 2, 2, 2, 7,
       2, 2, 7, 7, 7, 7, 7, 2, 7, 7, 7, 2, 2, 7, 7, 2, 2, 2, 2, 2, 2, 7,
       2, 2, 2, 2, 2, 4, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 7, 7, 2,
       2, 2, 7, 7, 7, 7, 7, 3, 2, 2, 2, 2, 2, 2, 2,

In [35]:
clusters_tdt2_last10.shape

(653,)

In [36]:
# purity of Kmeans clustering for Last 10 of TDT2
purity_kmeans_last10_tdt2=purity(10,Last10_tdt2,clusters_tdt2_last10)
purity_kmeans_last10_tdt2

0.4318529862174579

In [37]:
# entropy of Kmeans clustering for Top 10 of TDT2
entropy_kmeans_last10_tdt2=entropy(10,Last10_tdt2,clusters_tdt2_last10)
entropy_kmeans_last10_tdt2

0.6350631542660742

In [38]:
# NMF for Last 10 of TDT2
W_tdt2_last10,H_tdt2_last10=nmf(10,matrix_tdt2_last10)

In [39]:
W_tdt2_last10.shape

(653, 10)

In [40]:
H_tdt2_last10.shape

(10, 36771)

In [41]:
# clusters of documents with NMF for Last 10 of TDT2
max_index_tdt2_last10=[]
for document in W_tdt2_last10:
    max_index_tdt2_last10.append(np.argmax(document))
max_index_tdt2_last10

[5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 7,
 5,
 0,
 5,
 5,
 0,
 5,
 5,
 0,
 5,
 5,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 5,
 0,
 0,
 0,
 5,
 5,
 5,
 8,
 7,
 9,
 9,
 5,
 8,
 1,
 1,
 5,
 5,
 8,
 5,
 5,
 5,
 5,
 3,
 3,
 3,
 5,
 5,
 5,
 5,
 5,
 1,
 1,
 6,
 3,
 1,
 3,
 5,
 7,
 6,
 3,
 9,
 3,
 5,
 0,
 4,
 9,
 1,
 7,
 6,
 9,
 9,
 0,
 9,
 8,
 9,
 9,
 3,
 3,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 9,
 9,
 1,
 5,
 1,
 5,
 5,
 5,
 5,
 7,
 5,
 8,
 8,
 5,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 5,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 5,
 2,
 2,
 8,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [42]:
np.shape(max_index_tdt2_last10)

(653,)

In [43]:
# purity of NMF clustering for Last 10 of TDT2
purity_nmf_last10_tdt2=purity(10,Last10_tdt2,max_index_tdt2_last10)
purity_nmf_last10_tdt2

0.8177641653905053

In [44]:
# entropy of NMF clustering for Top 10 of TDT2
entropy_nmf_last10_tdt2=entropy(10,Last10_tdt2,max_index_tdt2_last10)
entropy_nmf_last10_tdt2

0.23441438872854614

In [45]:
# Reuters-21578 dataset
mat_reu = scipy.io.loadmat('Reuters21578.mat')
mat_reu

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN, Created on: Wed Jan 16 00:53:49 2008',
 '__version__': '1.0',
 '__globals__': [],
 'gnd': array([[ 1],
        [ 1],
        [ 1],
        ...,
        [63],
        [64],
        [65]], dtype=uint8),
 'trainIdx': array([[   1],
        [   2],
        [   3],
        ...,
        [8286],
        [8288],
        [8290]], dtype=uint16),
 'testIdx': array([[2674],
        [2675],
        [2676],
        ...,
        [8291],
        [8292],
        [8293]], dtype=uint16),
 'fea': <8293x18933 sparse matrix of type '<class 'numpy.float64'>'
 	with 389455 stored elements in Compressed Sparse Column format>}

In [46]:
fea_reu = mat_reu.get('fea')
gnd_reu = mat_reu.get('gnd')

In [47]:
# number of documents in each category
counter_reu = np.zeros((65))
for i in gnd_reu:
    counter_reu[i-1] = counter_reu[i-1] + 1
counter_reu=np.array(counter_reu)
counter_reu

array([3.713e+03, 2.055e+03, 3.210e+02, 2.980e+02, 2.450e+02, 1.970e+02,
       1.420e+02, 1.140e+02, 1.100e+02, 9.000e+01, 8.700e+01, 6.300e+01,
       6.000e+01, 5.300e+01, 4.500e+01, 4.500e+01, 4.400e+01, 4.200e+01,
       3.800e+01, 3.800e+01, 3.700e+01, 3.600e+01, 3.300e+01, 3.000e+01,
       2.700e+01, 2.400e+01, 2.300e+01, 2.000e+01, 1.900e+01, 1.800e+01,
       1.800e+01, 1.800e+01, 1.600e+01, 1.500e+01, 1.400e+01, 1.200e+01,
       1.100e+01, 1.100e+01, 1.100e+01, 1.000e+01, 1.000e+01, 9.000e+00,
       8.000e+00, 7.000e+00, 6.000e+00, 5.000e+00, 5.000e+00, 5.000e+00,
       4.000e+00, 4.000e+00, 4.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
       1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00])

In [48]:
Top10_reu = counter_reu[:10]
Top10_reu

array([3713., 2055.,  321.,  298.,  245.,  197.,  142.,  114.,  110.,
         90.])

In [49]:
num_top10_reu=np.sum(Top10_reu)
num_top10_reu

7285.0

In [50]:
Top10_reu_2=[]
Top10_reu_2.append(math.ceil(Top10_reu[0]*0.05))
Top10_reu_2.append(math.ceil(Top10_reu[1]*0.1))
for i in Top10_reu[2:]:
    Top10_reu_2.append(math.ceil(i*0.4))
Top10_reu_2

[186, 206, 129, 120, 98, 79, 57, 46, 44, 36]

In [51]:
num_top10_reu_2=np.sum(Top10_reu_2)
num_top10_reu_2

1001

In [52]:
matrix_reu = fea_reu.toarray()
matrix_reu

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [53]:
np.shape(matrix_reu)

(8293, 18933)

In [54]:
# Top 10 of Reuters
matrix_reu_top10=matrix_reu[:int(num_top10_reu)]
matrix_reu_top10

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 2., 1., ..., 0., 0., 0.]])

In [55]:
matrix_reu_top10.shape

(7285, 18933)

In [56]:
matrix_reu_top10_2 = []
e = 0
for i in range(10):
    tp = Top10_reu_2[i]
    indices = np.random.choice(range(e, e + int(Top10_reu[i])), size=tp, replace=False)
    mp = matrix_reu_top10[indices]
    
    for j in mp:
        matrix_reu_top10_2.append(list(j))
    
    e += int(Top10_reu[i])

In [57]:
np.shape(matrix_reu_top10_2)

(1001, 18933)

In [58]:
clusters_reu_top10=kmeans(10,matrix_reu_top10_2)

c:\Users\AFRAA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [59]:
clusters_reu_top10

array([6, 4, 4, ..., 6, 6, 6])

In [60]:
clusters_reu_top10.shape

(1001,)

In [61]:
purity_kmeans_top10_reu=purity(10,Top10_reu_2,clusters_reu_top10)
purity_kmeans_top10_reu

0.41058941058941056

In [62]:
entropy_kmeans_top10_reu=entropy(10,Top10_reu_2,clusters_reu_top10)
entropy_kmeans_top10_reu

0.741333893614782

In [63]:
W_reu_top10,H_reu_top10=nmf(10,matrix_reu_top10_2)

In [64]:
W_reu_top10.shape

(1001, 10)

In [65]:
H_reu_top10.shape

(10, 18933)

In [66]:
# clusters of documents with NMF for Top 10 of Reuters
max_index_reu_top10=[]
for document in W_reu_top10:
    max_index_reu_top10.append(np.argmax(document))
max_index_reu_top10

[3,
 3,
 0,
 3,
 5,
 3,
 5,
 3,
 3,
 3,
 3,
 3,
 3,
 8,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 3,
 5,
 4,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 3,
 8,
 5,
 5,
 7,
 7,
 5,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 3,
 3,
 3,
 0,
 3,
 8,
 3,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 5,
 5,
 5,
 0,
 3,
 3,
 3,
 3,
 5,
 3,
 7,
 3,
 7,
 8,
 3,
 3,
 3,
 3,
 3,
 3,
 7,
 7,
 0,
 3,
 8,
 8,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 3,
 7,
 3,
 3,
 0,
 7,
 3,
 3,
 3,
 7,
 3,
 3,
 3,
 8,
 3,
 3,
 3,
 3,
 3,
 7,
 3,
 3,
 3,
 8,
 3,
 7,
 3,
 7,
 3,
 3,
 5,
 3,
 3,
 3,
 3,
 3,
 7,
 3,
 5,
 3,
 3,
 3,
 3,
 5,
 7,
 3,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 5,
 3,
 5,
 3,
 3,
 3,
 0,
 7,
 3,
 0,
 0,
 0,
 8,
 3,
 3,
 5,
 3,
 7,
 0,
 7,
 7,
 7,
 7,
 5,
 7,
 7,
 4,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 0,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 5,
 7,
 7,
 7,
 7,
 7,
 7,
 4,
 7,
 7,
 5,
 7,
 0,
 0,
 7,
 7,
 7,
 4,
 0,
 7,
 7,
 7,
 7,
 7,


In [67]:
np.shape(max_index_reu_top10)

(1001,)

In [68]:
purity_nmf_top10_reu=purity(10,Top10_reu_2,max_index_reu_top10)
purity_nmf_top10_reu

0.6773226773226774

In [69]:
entropy_nmf_top10_reu=entropy(10,Top10_reu_2,max_index_reu_top10)
entropy_nmf_top10_reu

0.3980028869014295

In [70]:
Top20_reu = counter_reu[:20]
Top20_reu

array([3713., 2055.,  321.,  298.,  245.,  197.,  142.,  114.,  110.,
         90.,   87.,   63.,   60.,   53.,   45.,   45.,   44.,   42.,
         38.,   38.])

In [71]:
num_top20_reu=np.sum(Top20_reu)
num_top20_reu

7800.0

In [72]:
Top20_reu_2=[]
Top20_reu_2.append(math.ceil(Top20_reu[0]*0.05))
Top20_reu_2.append(math.ceil(Top20_reu[1]*0.1))
for i in Top20_reu[2:]:
    Top20_reu_2.append(math.ceil(i))
Top20_reu_2

[186,
 206,
 321,
 298,
 245,
 197,
 142,
 114,
 110,
 90,
 87,
 63,
 60,
 53,
 45,
 45,
 44,
 42,
 38,
 38]

In [73]:
num_top20_reu_2=np.sum(Top20_reu_2)
num_top20_reu_2


2424

In [74]:
# Top 20 of Reuters
matrix_reu_top20=matrix_reu[:int(num_top20_reu)]
matrix_reu_top20

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 2., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [75]:
matrix_reu_top20.shape

(7800, 18933)

In [76]:
matrix_reu_top20_2 = []
e = 0
for i in range(20):
    tp = Top20_reu_2[i]
    indices = np.random.choice(range(e, e + int(Top20_reu[i])), size=tp, replace=False)
    mp = matrix_reu_top20[indices]
    
    for j in mp:
        matrix_reu_top20_2.append(list(j))
    
    e += int(Top20_reu[i])

In [77]:
np.shape(matrix_reu_top20_2)

(2424, 18933)

In [78]:
clusters_reu_top20=kmeans(20,matrix_reu_top20_2)
clusters_reu_top20

c:\Users\AFRAA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


array([17, 17, 10, ..., 17, 17, 17])

In [79]:
clusters_reu_top20.shape

(2424,)

In [80]:
purity_kmeans_top20_reu=purity(20,Top20_reu_2,clusters_reu_top20)
purity_kmeans_top20_reu

0.37087458745874585

In [81]:
entropy_kmeans_top20_reu=entropy(20,Top20_reu_2,clusters_reu_top20)
entropy_kmeans_top20_reu

0.6491503157236743

In [82]:
W_reu_top20,H_reu_top20=nmf(20,matrix_reu_top20_2)

In [83]:
W_reu_top20.shape

(2424, 20)

In [84]:
H_reu_top20.shape

(20, 18933)

In [85]:
max_index_reu_top20=[]
for document in W_reu_top20:
    max_index_reu_top20.append(np.argmax(document))
max_index_reu_top20

[11,
 14,
 11,
 11,
 3,
 11,
 14,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 11,
 14,
 1,
 3,
 1,
 1,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 7,
 11,
 11,
 4,
 14,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 1,
 11,
 3,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 3,
 11,
 1,
 11,
 14,
 11,
 11,
 11,
 1,
 1,
 1,
 11,
 11,
 11,
 3,
 11,
 11,
 11,
 11,
 11,
 3,
 11,
 14,
 11,
 7,
 3,
 3,
 11,
 3,
 11,
 11,
 11,
 11,
 11,
 1,
 11,
 3,
 11,
 11,
 11,
 11,
 11,
 11,
 4,
 14,
 7,
 11,
 14,
 11,
 1,
 11,
 1,
 11,
 11,
 11,
 11,
 11,
 3,
 11,
 11,
 11,
 11,
 11,
 1,
 11,
 19,
 11,
 11,
 1,
 11,
 11,
 11,
 5,
 11,
 11,
 11,
 14,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 7,
 11,
 1,
 1,
 11,
 3,
 11,
 11,
 1,
 11,
 3,
 3,
 11,
 11,
 3,
 11,
 3,
 14,
 11,
 11,
 11,
 7,
 14,
 7,
 11,
 11,
 14,
 14,
 3,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 1,
 11,
 11,
 11,
 11,
 11,
 14,
 1,
 11,
 11,
 1,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 1,
 6,
 14,
 14,
 14,
 6,
 14,
 14,
 14,
 1,
 14,
 14,
 14,
 14,
 14,
 

In [86]:
np.shape(max_index_reu_top20)

(2424,)

In [87]:
purity_nmf_top20_reu=purity(20,Top20_reu_2,max_index_reu_top20)
purity_nmf_top20_reu

0.6035478547854786

In [88]:
entropy_nmf_top20_reu=entropy(20,Top20_reu_2,max_index_reu_top20)
entropy_nmf_top20_reu

0.4268007924330255

In [89]:
import pandas as pd
Comparison_table = pd.DataFrame({
    "Data set": ["TDT2_Top10","TDT2_Last10","Reuters_Top10","Reuters_Top20"],
    "Kmeans_purity": [purity_kmeans_top10_tdt2,purity_kmeans_last10_tdt2,purity_kmeans_top10_reu,purity_kmeans_top20_reu],
    "Kmeans_entropy": [entropy_kmeans_top10_tdt2,entropy_kmeans_last10_tdt2,entropy_kmeans_top10_reu,entropy_kmeans_top20_reu],
    "NMF_purity": [purity_nmf_top10_tdt2,purity_nmf_last10_tdt2,purity_nmf_top10_reu,purity_nmf_top20_reu],
    "NMF_entropy": [entropy_nmf_top10_tdt2,entropy_nmf_last10_tdt2,entropy_nmf_top10_reu,entropy_nmf_top20_reu]
})
Comparison_table

Data set  Kmeans_purity  Kmeans_entropy  NMF_purity  NMF_entropy
0     TDT2_Top10       0.366178        0.748810    0.822903     0.243538
1    TDT2_Last10       0.431853        0.635063    0.817764     0.234414
2  Reuters_Top10       0.410589        0.741334    0.677323     0.398003
3  Reuters_Top20       0.370875        0.649150    0.603548     0.426801